import { type FormEvent, useEffect, useRef, useState } from 'react';
import { adminService, studentAdminService } from '../../services';
import type { AdminClass, AdminModality, AdminPlan, Student, StudentStatus } from '../../types';

type Props = { student: Student; onClose: () => void; onSaved: () => Promise<unknown> };
const isoDay = (value: string) => new Date(value).toISOString().slice(0, 10);
export function EditStudentPanel({ student, onClose, onSaved }: Props) {
  const busy = useRef(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  const [plans,setPlans]=useState<AdminPlan[]>([]); const [modalities,setModalities]=useState<AdminModality[]>([]); const [classes,setClasses]=useState<AdminClass[]>([]);
  const [personal,setPersonal]=useState({name:student.person.name,cpf:student.person.cpf,email:student.person.email,phone:student.person.phone??'',status:student.status,joinedAt:isoDay(student.joinedAt),notes:student.notes??''});
  const activePlan=student.plans?.[0]; const [plan,setPlan]=useState({monthlyPrice:String(activePlan?.monthlyPrice??''),billingDay:String(activePlan?.billingDay??'')}); const [newModality,setNewModality]=useState(''); const [newClass,setNewClass]=useState('');
  useEffect(()=>{Promise.all([adminService.getPlans(),adminService.getModalities(),adminService.getClasses()]).then(([p,m,c])=>{setPlans(p);setModalities(m);setClasses(c);}).catch(e=>setError(e instanceof Error?e.message:'Erro ao carregar catálogos.'));},[]);
  const run=async(action:()=>Promise<unknown>,message:string)=>{if(busy.current)return;busy.current=true;setSaving(true);setError('');setSuccess('');try{await action();await onSaved();setSuccess(message);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{busy.current=false;setSaving(false);}};
  const savePersonal=(e:FormEvent)=>{e.preventDefault();void run(()=>Promise.all([studentAdminService.updatePerson(student.personId,{name:personal.name.trim(),cpf:personal.cpf.replace(/\D/g,''),email:personal.email.trim(),phone:personal.phone.trim()}),studentAdminService.updateStudent(student.id,{status:personal.status as StudentStatus,joinedAt:`${personal.joinedAt}T00:00:00.000Z`,notes:personal.notes.trim()})]),'Dados do aluno atualizados.');};
  const activeModalityIds=new Set(student.modalities?.filter(m=>m.status==='ACTIVE').map(m=>m.modality.id)); const availableClasses=classes.filter(c=>c.active&&activeModalityIds.has(c.modalityId)&&!student.studentClasses?.some(sc=>sc.class.id===c.id));
  return <div className="edit-student-backdrop" role="dialog" aria-modal="true"><div className="edit-student-panel"><header><div><p className="section-eyebrow">Edição operacional</p><h2>Editar aluno</h2></div><button onClick={onClose} disabled={saving}>Fechar</button></header>{error&&<div className="form-error">{error}</div>}{success&&<div className="admin-success">{success}</div>}
  <form className="edit-section" onSubmit={savePersonal}><h3>Dados pessoais e status</h3><div className="form-grid"><label>Nome<input required value={personal.name} onChange={e=>setPersonal({...personal,name:e.target.value})}/></label><label>CPF<input required value={personal.cpf} onChange={e=>setPersonal({...personal,cpf:e.target.value})}/></label><label>E-mail<input required type="email" value={personal.email} onChange={e=>setPersonal({...personal,email:e.target.value})}/></label><label>Telefone<input value={personal.phone} onChange={e=>setPersonal({...personal,phone:e.target.value})}/></label><label>Status<select value={personal.status} onChange={e=>setPersonal({...personal,status:e.target.value as StudentStatus})}><option value="ACTIVE">Ativo</option><option value="PAUSED">Pausado</option><option value="INACTIVE">Inativo</option></select></label><label>Data de entrada<input required type="date" value={personal.joinedAt} onChange={e=>setPersonal({...personal,joinedAt:e.target.value})}/></label><label className="wide-field">Observações<textarea value={personal.notes} onChange={e=>setPersonal({...personal,notes:e.target.value})}/></label></div><button className="open-student-button" disabled={saving}>Salvar dados</button></form>
  <section className="edit-section"><h3>Plano ativo</h3>{activePlan?<><p><strong>{activePlan.plan.name}</strong> · Início {isoDay(activePlan.startDate)} · {activePlan.status}</p><div className="inline-editor"><label>Valor mensal<input type="number" min="0" step="0.01" value={plan.monthlyPrice} onChange={e=>setPlan({...plan,monthlyPrice:e.target.value})}/></label><label>Vencimento<input type="number" min="1" max="31" value={plan.billingDay} onChange={e=>setPlan({...plan,billingDay:e.target.value})}/></label><button className="open-student-button" disabled={saving} onClick={()=>void run(()=>studentAdminService.updatePlan(activePlan.id,{monthlyPrice:Number(plan.monthlyPrice),billingDay:Number(plan.billingDay)}),'Condições do plano atualizadas.')}>Salvar plano</button></div><small>Troca de plano indisponível: o contrato atual não oferece transição atômica com preservação do histórico. Planos ativos disponíveis: {plans.filter(p=>p.active).map(p=>p.name).join(', ')||'nenhum'}.</small></>:<p>Nenhum plano ativo.</p>}</section>
  <section className="edit-section"><h3>Modalidades</h3>{student.modalities?.map(m=><div className="link-row" key={m.id}><span><strong>{m.modality.name}</strong><small>Início {isoDay(m.startedAt)} · {m.status}</small></span><button disabled={saving} onClick={()=>void run(()=>studentAdminService.updateModality(m.id,{status:m.status==='ACTIVE'?'PAUSED':'ACTIVE'}),`Modalidade ${m.status==='ACTIVE'?'desativada':'ativada'}.`)}>{m.status==='ACTIVE'?'Desativar':'Ativar'}</button></div>)}<div className="inline-editor"><select value={newModality} onChange={e=>setNewModality(e.target.value)}><option value="">Adicionar modalidade</option>{modalities.filter(m=>m.active&&!student.modalities?.some(sm=>sm.modality.id===m.id)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button disabled={saving||!newModality} onClick={()=>void run(()=>studentAdminService.addModality({studentId:student.id,modalityId:Number(newModality),startedAt:new Date().toISOString(),status:'ACTIVE'}),'Modalidade adicionada.')}>Adicionar</button></div></section>
  <section className="edit-section"><h3>Turmas</h3>{student.studentClasses?.map(sc=><div className="link-row" key={sc.id}><span><strong>{sc.class.name}</strong><small>{sc.class.modality.name} · {sc.class.teacher.name} · {sc.class.weekDays.join(', ')} · {sc.class.startTime}–{sc.class.endTime}</small></span><button disabled={saving} onClick={()=>void run(()=>studentAdminService.removeClass(sc.id),'Vínculo com turma removido.')}>Remover</button></div>)}<div className="inline-editor"><select value={newClass} onChange={e=>setNewClass(e.target.value)}><option value="">Adicionar turma compatível</option>{availableClasses.map(c=><option key={c.id} value={c.id}>{c.name} — {c.modality.name}</option>)}</select><button disabled={saving||!newClass} onClick={()=>void run(()=>studentAdminService.addClass({studentId:student.id,classId:Number(newClass)}),'Turma adicionada.')}>Adicionar</button></div></section>
  </div></div>;
}
