import { type FormEvent, useEffect, useRef, useState } from 'react';
import { adminService, studentAdminService } from '../../services';
import type { AdminClass, AdminModality, AdminPlan, Student, StudentStatus } from '../../types';

type Props = { student: Student; onClose: () => void; onSaved: () => Promise<unknown> };
const isoDay = (value: string) => new Date(value).toISOString().slice(0, 10);
export function EditStudentPanel({ student, onClose, onSaved }: Props) {
  const busy=useRef(false); const[saving,setSaving]=useState(false); const[error,setError]=useState('');
  const[plans,setPlans]=useState<AdminPlan[]>([]); const[modalities,setModalities]=useState<AdminModality[]>([]); const[classes,setClasses]=useState<AdminClass[]>([]);
  const[form,setForm]=useState({name:student.person.name,cpf:student.person.cpf,email:student.person.email,phone:student.person.phone??'',status:student.status,joinedAt:isoDay(student.joinedAt),notes:student.notes??'',planId:String(student.plans?.[0]?.plan.id??''),monthlyPrice:String(student.plans?.[0]?.monthlyPrice??''),billingDay:String(student.plans?.[0]?.billingDay??''),planStart:isoDay(student.plans?.[0]?.startDate??new Date().toISOString())});
  const[addModalities,setAddModalities]=useState<number[]>([]); const[deactivateModalities,setDeactivateModalities]=useState<number[]>([]); const[addClasses,setAddClasses]=useState<number[]>([]); const[removeClasses,setRemoveClasses]=useState<number[]>([]);
  useEffect(()=>{Promise.all([adminService.getPlans(),adminService.getModalities(),adminService.getClasses()]).then(([p,m,c])=>{setPlans(p);setModalities(m);setClasses(c);}).catch(e=>setError(e instanceof Error?e.message:'Erro ao carregar catálogos.'));},[]);
  const activeModalityIds=new Set([...(student.modalities?.filter(m=>m.status==='ACTIVE'&&!deactivateModalities.includes(m.id)).map(m=>m.modality.id)??[]),...addModalities]);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(busy.current)return;busy.current=true;setSaving(true);setError('');try{await studentAdminService.maintain(student.id,{person:{name:form.name.trim(),cpf:form.cpf.replace(/\D/g,''),email:form.email.trim(),phone:form.phone.trim()},student:{status:form.status as StudentStatus,joinedAt:`${form.joinedAt}T00:00:00.000Z`,notes:form.notes.trim()},...(form.planId?{plan:{planId:Number(form.planId),monthlyPrice:Number(form.monthlyPrice),billingDay:Number(form.billingDay),startDate:`${form.planStart}T00:00:00.000Z`}}:{}),addModalityIds:addModalities,deactivateStudentModalityIds:deactivateModalities,addClassIds:addClasses,removeStudentClassIds:removeClasses});await onSaved();onClose();}catch(c){setError(`${c instanceof Error?c.message:'Não foi possível salvar.'} Nenhuma alteração parcial foi aplicada.`);}finally{busy.current=false;setSaving(false);}};
  return <div className="edit-student-backdrop" role="dialog" aria-modal="true"><form className="edit-student-panel" onSubmit={submit}><header><div><p className="section-eyebrow">Edição transacional</p><h2>Editar aluno e matrícula</h2></div><button type="button" onClick={onClose} disabled={saving}>Cancelar</button></header>{error&&<div className="form-error">{error}</div>}
  <section className="edit-section"><h3>Dados pessoais e status</h3><div className="form-grid"><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>CPF<input required value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})}/></label><label>E-mail<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as StudentStatus})}><option value="ACTIVE">Ativo</option><option value="PAUSED">Pausado</option><option value="INACTIVE">Inativo</option></select></label><label>Data de entrada<input required type="date" value={form.joinedAt} onChange={e=>setForm({...form,joinedAt:e.target.value})}/></label><label className="wide-field">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></section>
  <section className="edit-section"><h3>Plano</h3><div className="form-grid"><label>Plano ativo/novo<select required value={form.planId} onChange={e=>{const p=plans.find(x=>x.id===Number(e.target.value));setForm({...form,planId:e.target.value,...(p?{monthlyPrice:String(p.price)}:{})});}}><option value="">Selecione</option>{plans.filter(p=>p.active||p.id===student.plans?.[0]?.plan.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Preço mensal<input required type="number" min="0" step="0.01" value={form.monthlyPrice} onChange={e=>setForm({...form,monthlyPrice:e.target.value})}/></label><label>Vencimento<input required type="number" min="1" max="31" value={form.billingDay} onChange={e=>setForm({...form,billingDay:e.target.value})}/></label><label>Início do vínculo<input required type="date" value={form.planStart} onChange={e=>setForm({...form,planStart:e.target.value})}/></label></div><small>Na troca, o plano anterior será finalizado. Cobranças e pagamentos existentes permanecerão inalterados.</small></section>
  <section className="edit-section"><h3>Modalidades</h3>{student.modalities?.map(m=><label className="link-row" key={m.id}><span><strong>{m.modality.name}</strong><small>Início {isoDay(m.startedAt)} · {m.status}</small></span>{m.status==='ACTIVE'&&<input type="checkbox" checked={!deactivateModalities.includes(m.id)} onChange={e=>setDeactivateModalities(e.target.checked?deactivateModalities.filter(id=>id!==m.id):[...deactivateModalities,m.id])}/>}</label>)}{modalities.filter(m=>m.active&&!student.modalities?.some(sm=>sm.modality.id===m.id)).map(m=><label className="link-row" key={m.id}><span>Adicionar {m.name}</span><input type="checkbox" checked={addModalities.includes(m.id)} onChange={e=>setAddModalities(e.target.checked?[...addModalities,m.id]:addModalities.filter(id=>id!==m.id))}/></label>)}</section>
  <section className="edit-section"><h3>Turmas</h3>{student.studentClasses?.map(sc=><label className="link-row" key={sc.id}><span><strong>{sc.class.name}</strong><small>{sc.class.modality.name} · {sc.class.teacher.name} · {sc.class.startTime}–{sc.class.endTime}</small></span><input type="checkbox" checked={!removeClasses.includes(sc.id)} onChange={e=>setRemoveClasses(e.target.checked?removeClasses.filter(id=>id!==sc.id):[...removeClasses,sc.id])}/></label>)}{classes.filter(c=>c.active&&activeModalityIds.has(c.modalityId)&&!student.studentClasses?.some(sc=>sc.class.id===c.id)).map(c=><label className="link-row" key={c.id}><span>Adicionar {c.name}<small>{c.modality.name} · {c.teacher.name}</small></span><input type="checkbox" checked={addClasses.includes(c.id)} onChange={e=>setAddClasses(e.target.checked?[...addClasses,c.id]:addClasses.filter(id=>id!==c.id))}/></label>)}</section>
  <div className="form-actions"><button type="submit" className="open-student-button" disabled={saving}>{saving?'Salvando tudo...':'Salvar todas as alterações'}</button></div></form></div>;
}
