import { type FormEvent, useEffect, useState } from 'react';
import { AdminLayout } from '../components/admin/AdminLayout';
import { adminService } from '../services';
import type { AdminPlan } from '../types';

const empty = { name: '', description: '', price: '', weeklyClasses: '1', active: true };
export function AdminPlansPage() {
  const [items, setItems] = useState<AdminPlan[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setItems(await adminService.getPlans()); } catch (e) { setError(e instanceof Error ? e.message : 'Erro ao carregar planos.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const body = { ...form, name: form.name.trim(), description: form.description.trim(), price: Number(form.price), weeklyClasses: Number(form.weeklyClasses) }; if (editing) await adminService.updatePlan(editing, body); else await adminService.createPlan(body); setMessage(editing ? 'Plano atualizado.' : 'Plano criado.'); setEditing(null); setForm(empty); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Erro ao salvar plano.'); } finally { setSaving(false); } };
  const edit = (item: AdminPlan) => { setEditing(item.id); setForm({ name: item.name, description: item.description, price: String(item.price), weeklyClasses: String(item.weeklyClasses), active: item.active }); setMessage(''); };
  const toggle = async (item: AdminPlan) => { setError(''); try { await adminService.updatePlan(item.id, { active: !item.active }); setMessage(`Plano ${item.active ? 'desativado' : 'ativado'}.`); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Erro ao alterar status.'); } };
  return <AdminLayout><section className="admin-grid"><form className="admin-form" onSubmit={submit}><h2>{editing ? 'Editar plano' : 'Novo plano'}</h2>{error && <div className="form-error">{error}</div>}{message && <div className="admin-success">{message}</div>}<label>Nome<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Descrição<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Preço<input required type="number" min="0" step="0.01" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /></label><label>Aulas semanais<input required type="number" min="0" step="1" value={form.weeklyClasses} onChange={(e) => setForm({ ...form, weeklyClasses: e.target.value })} /></label><label className="check-field"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} /> Ativo</label><div className="form-actions"><button className="open-student-button" disabled={saving}>{saving ? 'Salvando...' : 'Salvar'}</button>{editing && <button type="button" className="secondary-action-button" onClick={() => { setEditing(null); setForm(empty); }}>Cancelar</button>}</div></form><div className="admin-list"><h2>Planos</h2>{loading ? <div className="admin-state">Carregando...</div> : items.length === 0 ? <div className="admin-state">Nenhum plano cadastrado.</div> : <table><thead><tr><th>Nome</th><th>Preço</th><th>Aulas</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.description}</small></td><td>{Number(item.price).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</td><td>{item.weeklyClasses}</td><td>{item.active ? 'Ativo' : 'Inativo'}</td><td><button onClick={() => edit(item)}>Editar</button><button onClick={() => void toggle(item)}>{item.active ? 'Desativar' : 'Ativar'}</button></td></tr>)}</tbody></table>}</div></section></AdminLayout>;
}
