import { type FormEvent, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApiRequest } from '../hooks';
import { catalogService, reportsService } from '../services';
import type { ClassOption, ModalityOption } from '../types';
import type { AttendanceReportRow, FinancialReportRow, GraduationReportRow, ReportPage, StudentReportRow } from '../types/report';

type ReportKind = 'students' | 'financial' | 'attendance' | 'graduations';
const labels: Record<ReportKind, string> = { students: 'Alunos', financial: 'Financeiro', attendance: 'Presença', graduations: 'Graduação' };
const date = (value: string) => new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC' }).format(new Date(value));
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const belts = { WHITE: 'Branca', BLUE: 'Azul', PURPLE: 'Roxa', BROWN: 'Marrom', BLACK: 'Preta' } as const;

function Pager({ page, totalPages, onPage }: { page: number; totalPages: number; onPage: (page: number) => void }) {
  if (totalPages <= 1) return null;
  return <nav className="reports-pagination"><button disabled={page <= 1} onClick={() => onPage(page - 1)}>Anterior</button><span>Página {page} de {totalPages}</span><button disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Próxima</button></nav>;
}
function State<T>({ result, loading, error, children }: { result: ReportPage<T> | null; loading: boolean; error: Error | null; children: (rows: T[]) => React.ReactNode }) {
  if (loading) return <div className="reports-state"><span className="loading-spinner" /><p>Carregando relatório...</p></div>;
  if (error) return <div className="reports-state reports-error" role="alert"><strong>Não foi possível carregar o relatório.</strong><p>{error.message}</p></div>;
  if (result && result.data.length === 0) return <div className="reports-state">Nenhum registro encontrado para os filtros informados.</div>;
  return result ? <>{children(result.data)}</> : null;
}

function StudentsReport({ modalities }: { modalities: ModalityOption[] }) {
  const initial = { status: '', modalityId: '', joinedFrom: '', joinedTo: '' };
  const [filters, setFilters] = useState(initial); const { data, loading, error, execute } = useApiRequest<ReportPage<StudentReportRow>, [Record<string, string | number | undefined>]>();
  const search = (page = 1, values = filters) => execute(reportsService.students, { ...values, modalityId: values.modalityId || undefined, page, pageSize: 20 });
  useEffect(() => { void search(); }, []);
  return <section className="reports-panel"><form className="reports-filters" onSubmit={(e) => { e.preventDefault(); void search(1); }}><label>Status<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Todos</option><option value="ACTIVE">Ativo</option><option value="PAUSED">Pausado</option><option value="INACTIVE">Inativo</option></select></label><label>Modalidade<select value={filters.modalityId} onChange={(e) => setFilters({ ...filters, modalityId: e.target.value })}><option value="">Todas</option>{modalities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Entrada de<input type="date" value={filters.joinedFrom} onChange={(e) => setFilters({ ...filters, joinedFrom: e.target.value })} /></label><label>Entrada até<input type="date" value={filters.joinedTo} onChange={(e) => setFilters({ ...filters, joinedTo: e.target.value })} /></label><button>Pesquisar</button><button type="button" onClick={() => { setFilters(initial); void search(1, initial); }}>Limpar</button></form><State result={data} loading={loading} error={error}>{(rows) => <div className="reports-table-scroll"><table><thead><tr><th>Nome</th><th>Matrícula</th><th>Status</th><th>Modalidades</th><th>Entrada</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.enrollmentNumber}</td><td>{row.status}</td><td>{row.modalities.join(', ') || '—'}</td><td>{date(row.joinedAt)}</td></tr>)}</tbody></table></div>}</State>{data && <Pager page={data.page} totalPages={data.totalPages} onPage={(page) => void search(page)} />}</section>;
}

function FinancialReport() {
  const initial = { status: '', dueFrom: '', dueTo: '' }; const [filters, setFilters] = useState(initial); const { data, loading, error, execute } = useApiRequest<ReportPage<FinancialReportRow>, [Record<string, string | number | undefined>]>();
  const search = (page = 1, values = filters) => execute(reportsService.financial, { ...values, page, pageSize: 20 }); useEffect(() => { void search(); }, []);
  return <section className="reports-panel"><form className="reports-filters" onSubmit={(e) => { e.preventDefault(); void search(1); }}><label>Status<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Todos</option>{['PENDING','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED','REFUNDED'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Vencimento de<input type="date" value={filters.dueFrom} onChange={(e) => setFilters({ ...filters, dueFrom: e.target.value })} /></label><label>Vencimento até<input type="date" value={filters.dueTo} onChange={(e) => setFilters({ ...filters, dueTo: e.target.value })} /></label><button>Pesquisar</button><button type="button" onClick={() => { setFilters(initial); void search(1, initial); }}>Limpar</button></form><State result={data} loading={loading} error={error}>{(rows) => <div className="reports-table-scroll"><table><thead><tr><th>Competência</th><th>Aluno</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Pago válido</th><th>Saldo</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.referenceMonth}</td><td>{row.student}</td><td>{money(row.amount)}</td><td>{date(row.dueDate)}</td><td>{row.status}</td><td>{money(row.totalPaid)}</td><td>{money(row.balance)}</td></tr>)}</tbody></table></div>}</State>{data && <Pager page={data.page} totalPages={data.totalPages} onPage={(page) => void search(page)} />}</section>;
}

function AttendanceReport({ classes }: { classes: ClassOption[] }) {
  const initial = { studentName: '', classId: '', status: '', dateFrom: '', dateTo: '' }; const [filters, setFilters] = useState(initial); const { data, loading, error, execute } = useApiRequest<ReportPage<AttendanceReportRow>, [Record<string, string | number | undefined>]>();
  const search = (page = 1, values = filters) => execute(reportsService.attendance, { ...values, classId: values.classId || undefined, page, pageSize: 20 }); useEffect(() => { void search(); }, []);
  return <section className="reports-panel"><form className="reports-filters" onSubmit={(e) => { e.preventDefault(); void search(1); }}><label>Aluno<input value={filters.studentName} onChange={(e) => setFilters({ ...filters, studentName: e.target.value })} placeholder="Nome do aluno" /></label><label>Turma<select value={filters.classId} onChange={(e) => setFilters({ ...filters, classId: e.target.value })}><option value="">Todas</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Status<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Todos</option><option value="PRESENT">Presente</option><option value="ABSENT">Ausente</option><option value="JUSTIFIED">Justificada</option></select></label><label>Data de<input type="date" value={filters.dateFrom} onChange={(e) => setFilters({ ...filters, dateFrom: e.target.value })} /></label><label>Data até<input type="date" value={filters.dateTo} onChange={(e) => setFilters({ ...filters, dateTo: e.target.value })} /></label><button>Pesquisar</button><button type="button" onClick={() => { setFilters(initial); void search(1, initial); }}>Limpar</button></form><State result={data} loading={loading} error={error}>{(rows) => <div className="reports-table-scroll"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Data</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.student}</td><td>{row.class}</td><td>{date(row.date)}</td><td>{row.status}</td></tr>)}</tbody></table></div>}</State>{data && <Pager page={data.page} totalPages={data.totalPages} onPage={(page) => void search(page)} />}</section>;
}

function GraduationsReport({ modalities }: { modalities: ModalityOption[] }) {
  const initial = { modalityId: '', belt: '', dateFrom: '', dateTo: '' }; const [filters, setFilters] = useState(initial); const { data, loading, error, execute } = useApiRequest<ReportPage<GraduationReportRow>, [Record<string, string | number | undefined>]>();
  const search = (page = 1, values = filters) => execute(reportsService.graduations, { ...values, modalityId: values.modalityId || undefined, page, pageSize: 20 }); useEffect(() => { void search(); }, []);
  return <section className="reports-panel"><form className="reports-filters" onSubmit={(e) => { e.preventDefault(); void search(1); }}><label>Modalidade<select value={filters.modalityId} onChange={(e) => setFilters({ ...filters, modalityId: e.target.value })}><option value="">Todas</option>{modalities.filter((item) => item.hasGraduation).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Faixa<select value={filters.belt} onChange={(e) => setFilters({ ...filters, belt: e.target.value })}><option value="">Todas</option>{Object.entries(belts).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Data de<input type="date" value={filters.dateFrom} onChange={(e) => setFilters({ ...filters, dateFrom: e.target.value })} /></label><label>Data até<input type="date" value={filters.dateTo} onChange={(e) => setFilters({ ...filters, dateTo: e.target.value })} /></label><button>Pesquisar</button><button type="button" onClick={() => { setFilters(initial); void search(1, initial); }}>Limpar</button></form><State result={data} loading={loading} error={error}>{(rows) => <div className="reports-table-scroll"><table><thead><tr><th>Aluno</th><th>Modalidade</th><th>Faixa</th><th>Data</th><th>Responsável</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.student}</td><td>{row.modality}</td><td>{belts[row.belt]}</td><td>{date(row.date)}</td><td>{row.actor ?? 'Não registrado'}</td></tr>)}</tbody></table></div>}</State>{data && <Pager page={data.page} totalPages={data.totalPages} onPage={(page) => void search(page)} />}</section>;
}

export function ReportsPage() {
  const navigate = useNavigate(); const [active, setActive] = useState<ReportKind>('students'); const [modalities, setModalities] = useState<ModalityOption[]>([]); const [classes, setClasses] = useState<ClassOption[]>([]);
  useEffect(() => { void Promise.all([catalogService.getModalities(), catalogService.getClasses()]).then(([m,c]) => { setModalities(m); setClasses(c); }); }, []);
  return <main className="students-page"><header className="students-page-header"><div><p className="section-eyebrow">Consulta operacional</p><h1>Relatórios</h1><p>Dados reais, filtrados e paginados.</p></div><button className="secondary-action-button" onClick={() => navigate('/dashboard')}>Voltar ao Dashboard</button></header><nav className="reports-nav">{(Object.keys(labels) as ReportKind[]).map((kind) => <button key={kind} className={active === kind ? 'active' : ''} onClick={() => setActive(kind)}>{labels[kind]}</button>)}</nav>{active === 'students' && <StudentsReport modalities={modalities} />}{active === 'financial' && <FinancialReport />}{active === 'attendance' && <AttendanceReport classes={classes} />}{active === 'graduations' && <GraduationsReport modalities={modalities} />}</main>;
}
