import { useCallback, useMemo, useState, type FormEvent } from 'react';
import { useAuth, useSelfServiceResource } from '../hooks';
import { storeOperations } from '../services';
import type { InternalStoreOrder } from '../services/store-operations.service';
import './store-operations.css';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' });
const stockLabels: Record<string, string> = { NORMAL: 'ESTOQUE NORMAL', LOW_STOCK: 'ESTOQUE ACABANDO', OUT_OF_STOCK: 'SEM ESTOQUE', MADE_TO_ORDER: 'SOB ENCOMENDA' };
const statusLabels: Record<string, string> = { PENDING_PAYMENT: 'Pagamento pendente', PAYMENT_REVIEW: 'Pagamento em análise', CONFIRMED: 'Confirmado', IN_PRODUCTION: 'Em fabricação', AWAITING_DELIVERY: 'Aguardando entrega', READY_FOR_PICKUP: 'Venha buscar seu produto', COMPLETED: 'Concluído', CANCELLED: 'Cancelado', UNDER_REVIEW: 'Em análise' };
type Tab = 'sale' | 'products' | 'stock' | 'entries' | 'reviews' | 'orders';
type DraftSale = { cpf: string; variantId: number; quantity: number; method: string; amount: number };

export function StoreOperationsPage() {
  const { user } = useAuth(); const admin = user?.role === 'OWNER' || user?.role === 'ADMIN';
  const [tab, setTab] = useState<Tab>(admin ? 'products' : 'sale'); const [message, setMessage] = useState(''); const [failed, setFailed] = useState(false);
  const [customer, setCustomer] = useState<{ name: string; enrollmentNumber: string; status: string } | null>(null); const [draft, setDraft] = useState<DraftSale | null>(null); const [selectedOrder, setSelectedOrder] = useState<InternalStoreOrder | null>(null);
  const [saleVariantId, setSaleVariantId] = useState(''); const [saleQuantity, setSaleQuantity] = useState(1); const [saleMethod, setSaleMethod] = useState('PIX_QR_CODE');
  const load = useCallback(async () => ({ products: await storeOperations.products(), reviews: admin ? await storeOperations.reviews() : [], orders: admin ? await storeOperations.orders() : [] }), [admin]);
  const resource = useSelfServiceResource(load, [load]);
  const variants = useMemo(() => resource.data?.products.flatMap((product) => product.variants.map((variant) => ({ ...variant, product }))) ?? [], [resource.data]);
  const saleVariant = variants.find((variant) => variant.id === Number(saleVariantId)); const saleTotal = (saleVariant?.product.salePrice ?? 0) * saleQuantity;
  const run = async (operation: () => Promise<unknown>, success = 'Operação registrada com sucesso.') => { setMessage(''); try { await operation(); setFailed(false); setMessage(success); await resource.refresh(); } catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : 'Não foi possível concluir. Tente novamente.'); } };
  const findCustomer = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); try { const found = await storeOperations.findCustomer(String(new FormData(event.currentTarget).get('cpf'))); setCustomer(found); setFailed(false); } catch (error) { setCustomer(null); setFailed(true); setMessage(error instanceof Error ? error.message : 'Cliente não encontrado.'); } };
  const prepareSale = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const next = { cpf: String(data.get('cpf')), variantId: Number(data.get('variantId')), quantity: Number(data.get('quantity')), method: String(data.get('method')), amount: Number(data.get('amount')) }; if (!customer) { setFailed(true); setMessage('Localize e confirme o cliente antes de continuar.'); return; } setDraft(next); };
  const confirmSale = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!draft) return; const justification = String(new FormData(event.currentTarget).get('justification')); void run(() => storeOperations.createOrder({ cpf: draft.cpf, items: [{ variantId: draft.variantId, quantity: draft.quantity }], paymentMethod: draft.method, paymentAmount: draft.amount, justification }), draft.method === 'PIX_MANUAL' || draft.method === 'CREDIT_CARD_PHYSICAL' ? 'Venda criada. Pagamento em análise.' : 'Pedido criado. Aguardando confirmação real do pagamento.').finally(() => setDraft(null)); };
  const createProduct = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.createProduct({ name: data.get('name'), description: data.get('description'), type: data.get('type'), salePrice: Number(data.get('salePrice')), madeToOrder: data.get('madeToOrder') === 'on', leadTimeDays: Number(data.get('leadTimeDays')), variants: [{ color: data.get('color'), size: data.get('size'), minimumStock: Number(data.get('minimumStock')) }] })); };
  const tabs: Array<{ id: Tab; label: string }> = admin ? [{ id: 'products', label: 'Produtos' }, { id: 'stock', label: 'Estoque' }, { id: 'entries', label: 'Entradas' }, { id: 'reviews', label: `Pagamentos em análise${resource.data?.reviews.length ? ` (${resource.data.reviews.length})` : ''}` }, { id: 'orders', label: 'Pedidos' }, { id: 'sale', label: 'Nova venda' }] : [{ id: 'sale', label: 'Nova venda' }];

  return <main className="students-page store-operations"><header className="store-page-header"><div><p className="section-eyebrow">Loja</p><h1>Operação comercial</h1><p>{admin ? 'Produtos, estoque, pagamentos e pedidos em áreas objetivas.' : 'Nova venda em poucos passos, com confirmação segura.'}</p></div></header>
    <nav className="store-tabs" aria-label="Áreas da Loja">{tabs.map((item) => <button key={item.id} type="button" className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {message && <p role={failed ? 'alert' : 'status'} className={`store-feedback ${failed ? 'error' : ''}`}>{message}</p>}
    {resource.loading && <section className="store-state" aria-live="polite"><span className="student-spinner" />Carregando Loja...</section>}
    {resource.error && <section className="store-state error"><h2>Não foi possível carregar a Loja</h2><p>Confira sua conexão e tente novamente.</p><button type="button" onClick={() => void resource.refresh()}>Tentar novamente</button></section>}
    {!resource.loading && !resource.error && tab === 'sale' && <section className="store-panel"><header><span className="store-step">1</span><div><h2>Cliente</h2><p>Busque pelo CPF e confirme apenas os dados necessários.</p></div></header><form className="store-inline" onSubmit={findCustomer}><label>CPF<input name="cpf" inputMode="numeric" required /></label><button type="submit">Localizar cliente</button></form>{customer && <div className="store-customer" role="status"><strong>{customer.name}</strong><span>Matrícula {customer.enrollmentNumber}</span><span>{customer.status}</span></div>}<header><span className="store-step">2</span><div><h2>Produto e pagamento</h2><p>O preço e o total são confirmados pelo servidor.</p></div></header><form className="store-form" onSubmit={prepareSale}><label>CPF confirmado<input name="cpf" required /></label><label>Produto, cor e tamanho<select name="variantId" value={saleVariantId} onChange={(event) => setSaleVariantId(event.target.value)} required><option value="">Selecione</option>{variants.map((variant) => <option key={variant.id} value={variant.id} disabled={!variant.product.madeToOrder && variant.availableQuantity < 1}>{variant.product.name} · {[variant.color, variant.size].filter(Boolean).join(' · ') || 'Padrão'} · {money.format(variant.product.salePrice)}</option>)}</select></label><label>Quantidade<input name="quantity" type="number" min="1" value={saleQuantity} onChange={(event) => setSaleQuantity(Math.max(1, Number(event.target.value)))} required /></label><label>Valor do pagamento<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Pagamento<select name="method" value={saleMethod} onChange={(event) => setSaleMethod(event.target.value)}><option value="PIX_QR_CODE">Pix QR Code</option><option value="CREDIT_CARD_LINK">Link de cartão</option><option value="CREDIT_CARD_PHYSICAL">Cartão físico</option><option value="PIX_MANUAL">Pix manual</option></select></label>{saleVariant && <div className="store-sale-total" role="status"><span>Unitário {money.format(saleVariant.product.salePrice)}</span><strong>Total {money.format(saleTotal)}</strong><small>Valor final confirmado no servidor</small></div>}<button type="submit">{saleMethod === 'PIX_MANUAL' || saleMethod === 'CREDIT_CARD_PHYSICAL' ? 'Marcar como pago' : 'Revisar venda'}</button></form><p className="store-help">Pix QR Code e link permanecem pendentes até confirmação eletrônica real. Nenhuma confirmação é simulada.</p></section>}
    {admin && !resource.loading && !resource.error && tab === 'products' && <section className="store-panel"><header><div><h2>Produtos</h2><p>Cadastro e visão comercial autorizada.</p></div></header><form className="store-form" onSubmit={createProduct}><label>Nome<input name="name" required /></label><label>Tipo<select name="type"><option value="SHIRT">Camisa</option><option value="SHORTS">Short</option><option value="SET">Conjunto</option></select></label><label className="wide-field">Descrição<textarea name="description" required /></label><label>Venda<input name="salePrice" type="number" min="0" step="0.01" required /></label><label>Cor<input name="color" /></label><label>Tamanho<input name="size" /></label><label>Estoque mínimo<input name="minimumStock" type="number" min="0" defaultValue="0" /></label><label>Prazo em dias<input name="leadTimeDays" type="number" min="1" defaultValue="7" /></label><label className="store-check"><input name="madeToOrder" type="checkbox" /> Sob encomenda</label><button type="submit">Criar produto</button></form><div className="store-table-wrap"><table><thead><tr><th>Produto</th><th>Tipo</th><th>Variações</th><th>Custo</th><th>Venda</th><th>Status</th></tr></thead><tbody>{resource.data?.products.map((product) => <tr key={product.id}><td>{product.name}</td><td>{product.type}</td><td>{product.variants.length}</td><td>{money.format(product.variants[0]?.latestUnitCost ?? 0)}</td><td>{money.format(product.salePrice)}</td><td>{product.madeToOrder ? 'SOB ENCOMENDA' : product.status}</td></tr>)}</tbody></table></div></section>}
    {admin && !resource.loading && !resource.error && tab === 'stock' && <section className="store-panel"><header><div><h2>Estoque</h2><p>Quantidade atual, mínimo e estado por variação.</p></div></header><div className="store-table-wrap"><table><thead><tr><th>Produto</th><th>Variação</th><th>Atual</th><th>Mínimo</th><th>Status</th></tr></thead><tbody>{variants.map((variant) => <tr key={variant.id}><td>{variant.product.name}</td><td>{[variant.color, variant.size].filter(Boolean).join(' · ') || 'Padrão'}</td><td>{variant.availableQuantity}</td><td>{variant.minimumStock}</td><td><span className={`store-badge ${variant.stockState.toLowerCase()}`}>{stockLabels[variant.stockState]}</span></td></tr>)}</tbody></table></div></section>}
    {admin && !resource.loading && !resource.error && tab === 'entries' && <section className="store-panel"><header><div><h2>Registrar entrada</h2><p>Entrada positiva com quantidade e custo obrigatórios.</p></div></header><form className="store-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.addStock(Number(data.get('variantId')), Number(data.get('quantity')), Number(data.get('unitCost'))), 'Entrada registrada. Estoque atualizado.'); }}><label>Produto e variação<select name="variantId" required><option value="">Selecione</option>{variants.map((variant) => <option key={variant.id} value={variant.id}>{variant.product.name} · {[variant.color, variant.size].filter(Boolean).join(' · ') || 'Padrão'}</option>)}</select></label><label>Quantidade<input name="quantity" type="number" min="1" required /></label><label>Custo unitário<input name="unitCost" type="number" min="0" step="0.01" required /></label><button type="submit">Registrar entrada</button></form></section>}
    {admin && !resource.loading && !resource.error && tab === 'reviews' && <section className="store-panel"><header><div><h2>Pagamentos em análise</h2><p>Esta fila é o canal interno de pendências disponível.</p></div></header>{resource.data?.reviews.length ? <div className="store-cards">{resource.data.reviews.map((review) => <article key={review.id}><div><strong>{review.order.student.person.name}</strong><span>Pedido #{review.orderId} · {review.order.student.enrollmentNumber}</span></div><dl><div><dt>Valor</dt><dd>{money.format(Number(review.amount))}</dd></div><div><dt>Método</dt><dd>{review.method.replace(/_/g, ' ')}</dd></div><div><dt>Data</dt><dd>{date.format(new Date(review.submittedAt))}</dd></div></dl><p><strong>Justificativa:</strong> {review.justification}</p><div className="store-actions"><button type="button" onClick={() => void run(() => storeOperations.approve(review.id, 'Conferido pela administração'), 'Pagamento confirmado.')}>Aprovar</button><button type="button" className="danger" onClick={() => void run(() => storeOperations.cancel(review.orderId, 'Pagamento manual não aprovado', false), 'Pedido cancelado.')}>Recusar / cancelar</button></div></article>)}</div> : <div className="store-empty"><h3>Nenhum pagamento em análise</h3><p>Novas pendências aparecerão aqui.</p></div>}</section>}
    {admin && !resource.loading && !resource.error && tab === 'orders' && <section className="store-panel"><header><div><h2>Pedidos</h2><p>Acompanhamento operacional e financeiro da Loja.</p></div></header>{resource.data?.orders.length ? <div className="store-cards">{resource.data.orders.map((order) => <article key={order.id}><div><strong>Pedido #{order.id} · {order.student.person.name}</strong><span>{order.student.enrollmentNumber} · {date.format(new Date(order.createdAt))}</span></div><dl><div><dt>Total</dt><dd>{money.format(order.total)}</dd></div><div><dt>Pago</dt><dd>{money.format(order.paid)}</dd></div><div><dt>Saldo</dt><dd>{money.format(order.balance)}</dd></div></dl><span className="store-badge">{statusLabels[order.status] ?? order.status}</span><button type="button" onClick={() => setSelectedOrder(order)}>Ver detalhes</button></article>)}</div> : <div className="store-empty"><h3>Nenhum pedido</h3><p>Pedidos reais aparecerão aqui.</p></div>}</section>}
    {draft && <div className="store-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDraft(null); }}><section className="store-modal" role="dialog" aria-modal="true" aria-labelledby="payment-modal-title"><h2 id="payment-modal-title">{draft.method === 'PIX_MANUAL' || draft.method === 'CREDIT_CARD_PHYSICAL' ? 'Marcar como pago' : 'Criar pedido'}</h2><p>Valor informado: <strong>{money.format(draft.amount)}</strong></p><p>{draft.method === 'PIX_MANUAL' || draft.method === 'CREDIT_CARD_PHYSICAL' ? 'A recepção não confirma o pagamento. O registro será enviado para análise de ADM/OWNER.' : 'O pagamento permanecerá pendente até uma confirmação eletrônica real.'}</p><form onSubmit={confirmSale}>{(draft.method === 'PIX_MANUAL' || draft.method === 'CREDIT_CARD_PHYSICAL') && <label>Justificativa obrigatória<textarea name="justification" autoFocus required /></label>}<div className="store-actions"><button type="button" className="secondary" onClick={() => setDraft(null)}>Voltar</button><button type="submit">{draft.method === 'PIX_MANUAL' || draft.method === 'CREDIT_CARD_PHYSICAL' ? 'Enviar para análise' : 'Confirmar pedido'}</button></div></form></section></div>}
    {selectedOrder && <div className="store-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setSelectedOrder(null); }}><section className="store-modal store-order-modal" role="dialog" aria-modal="true" aria-labelledby="order-modal-title"><h2 id="order-modal-title">Pedido #{selectedOrder.id}</h2><p><strong>{selectedOrder.student.person.name}</strong> · {statusLabels[selectedOrder.status] ?? selectedOrder.status}</p>{selectedOrder.items.map((item) => <div className="store-order-item" key={item.id}><span>{item.productName} · {[item.color, item.size].filter(Boolean).join(' · ') || 'Padrão'} · {item.quantity} un.</span><strong>{money.format(item.subtotal)}</strong>{item.madeToOrder && <small>Sob encomenda</small>}</div>)}<label>Atualizar acompanhamento<select defaultValue={selectedOrder.status} onChange={(event) => void run(() => storeOperations.updateOrderStatus(selectedOrder.id, event.target.value), 'Status do pedido atualizado.').then(() => setSelectedOrder(null))}><option value={selectedOrder.status}>{statusLabels[selectedOrder.status] ?? selectedOrder.status}</option><option value="IN_PRODUCTION">Em fabricação</option><option value="AWAITING_DELIVERY">Aguardando entrega</option><option value="READY_FOR_PICKUP">Venha buscar seu produto</option><option value="COMPLETED">Concluído</option></select></label><button type="button" className="secondary" onClick={() => setSelectedOrder(null)}>Fechar</button></section></div>}
  </main>;
}
