import { useCallback, useState, type FormEvent } from 'react';
import { useAuth, useSelfServiceResource } from '../hooks';
import { storeOperations } from '../services';
import './store-operations.css';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const stockLabels: Record<string, string> = { NORMAL: 'ESTOQUE NORMAL', LOW_STOCK: 'ESTOQUE ACABANDO', OUT_OF_STOCK: 'SEM ESTOQUE', MADE_TO_ORDER: 'SOB ENCOMENDA' };

export function StoreOperationsPage() {
  const { user } = useAuth();
  const canApprove = user?.role === 'OWNER' || user?.role === 'ADMIN';
  const load = useCallback(async () => ({ products: await storeOperations.products(), reviews: canApprove ? await storeOperations.reviews() : [] }), [canApprove]);
  const resource = useSelfServiceResource(load, [load]);
  const [message, setMessage] = useState('');
  const [customer, setCustomer] = useState<{ name: string; enrollmentNumber: string; status: string } | null>(null);
  const run = async (operation: () => Promise<unknown>) => { setMessage(''); try { await operation(); setMessage('Operação registrada com sucesso.'); await resource.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível concluir.'); } };
  const findCustomer = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const cpf = String(new FormData(event.currentTarget).get('cpf')); try { setCustomer(await storeOperations.findCustomer(cpf)); } catch (error) { setCustomer(null); setMessage(error instanceof Error ? error.message : 'Cliente não encontrado.'); } };
  const createSale = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.createOrder({ cpf: data.get('cpf'), items: [{ variantId: Number(data.get('variantId')), quantity: Number(data.get('quantity')) }], paymentMethod: data.get('method'), paymentAmount: Number(data.get('amount')), justification: data.get('justification') })); };
  const submitInstallment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.submitManualPayment(Number(data.get('orderId')), { method: data.get('method'), amount: Number(data.get('amount')), justification: data.get('justification') })); };
  const createProduct = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.createProduct({ name: data.get('name'), description: data.get('description'), type: data.get('type'), salePrice: Number(data.get('salePrice')), madeToOrder: data.get('madeToOrder') === 'on', leadTimeDays: Number(data.get('leadTimeDays')), variants: [{ color: data.get('color'), size: data.get('size'), minimumStock: Number(data.get('minimumStock')) }] })); };

  return <main className="students-page store-operations"><header className="students-page-header"><div><p className="section-eyebrow">Loja</p><h1>Operação comercial</h1><p>Produtos, estoque, vendas e análises em um fluxo simples.</p></div></header>
    {message && <p role="status" className="form-message">{message}</p>}
    {canApprove && <section className="student-card"><h2>Novo produto</h2><form className="form-grid" onSubmit={createProduct}><label>Nome<input name="name" required /></label><label>Tipo<select name="type"><option value="SHIRT">Camisa</option><option value="SHORTS">Short</option><option value="SET">Conjunto</option></select></label><label className="wide-field">Descrição<textarea name="description" required /></label><label>Valor de venda<input name="salePrice" type="number" min="0" step="0.01" required /></label><label>Cor<input name="color" /></label><label>Tamanho<input name="size" /></label><label>Estoque mínimo<input name="minimumStock" type="number" min="0" defaultValue="0" /></label><label>Prazo em dias<input name="leadTimeDays" type="number" min="1" defaultValue="7" /></label><label><input name="madeToOrder" type="checkbox" /> Produto sob encomenda</label><button type="submit">Criar produto</button></form><h3>Atualizar produto ou foto</h3><form className="inline-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.updateProduct(Number(data.get('productId')), { salePrice: Number(data.get('salePrice')), status: data.get('status') })); }}><label>Produto<input name="productId" type="number" min="1" required /></label><label>Valor de venda<input name="salePrice" type="number" min="0" step="0.01" required /></label><label>Status<select name="status"><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option><option value="OUT_OF_STOCK">Sem estoque</option><option value="MADE_TO_ORDER">Sob encomenda</option></select></label><button type="submit">Atualizar</button></form><form className="inline-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get('file'); if (file instanceof File) void run(() => storeOperations.uploadProductImage(Number(data.get('productId')), file)); }}><label>Produto<input name="productId" type="number" min="1" required /></label><label>Foto<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required /></label><button type="submit">Enviar foto</button></form></section>}
    <section className="student-card"><h2>Produtos e estoque</h2>{resource.loading ? <p>Carregando...</p> : <div className="student-list">{resource.data?.products.map((product) => <article key={product.id}><div><strong>{product.name} · {money.format(product.salePrice)}</strong>{product.variants.map((variant) => <div key={variant.id}><small>{[variant.color, variant.size].filter(Boolean).join(' · ') || 'Padrão'} · {variant.availableQuantity} un. · {stockLabels[variant.stockState]}</small>{canApprove && <form className="inline-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.addStock(variant.id, Number(data.get('quantity')), Number(data.get('unitCost')))); }}><input aria-label={`Quantidade de entrada ${product.name}`} name="quantity" type="number" min="1" required /><input aria-label={`Custo de entrada ${product.name}`} name="unitCost" type="number" min="0" step="0.01" required /><button type="submit">Registrar entrada</button></form>}</div>)}</div></article>)}</div>}</section>
    <section className="student-card"><h2>Venda pela recepção</h2><form className="inline-form" onSubmit={findCustomer}><label>CPF<input name="cpf" required /></label><button type="submit">Localizar cliente</button></form>{customer && <p><strong>{customer.name}</strong> · {customer.enrollmentNumber} · {customer.status}</p>}<form className="form-grid" onSubmit={createSale}><label>CPF confirmado<input name="cpf" required /></label><label>Produto / variação<select name="variantId" required><option value="">Selecione</option>{resource.data?.products.flatMap((product) => product.variants.map((variant) => <option key={variant.id} value={variant.id}>{product.name} · {[variant.color, variant.size].filter(Boolean).join(' · ') || 'Padrão'}</option>))}</select></label><label>Quantidade<input name="quantity" type="number" min="1" required /></label><label>Valor informado para pagamento<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Método<select name="method"><option value="PIX_MANUAL">Pix manual</option><option value="CREDIT_CARD_PHYSICAL">Cartão físico</option><option value="PIX_QR_CODE">Pix QR Code</option><option value="CREDIT_CARD_LINK">Link de cartão</option></select></label><label className="wide-field">Justificativa para pagamento manual/físico<textarea name="justification" /></label><button type="submit">Criar venda</button></form><h3>Registrar parcela manual para análise</h3><form className="form-grid" onSubmit={submitInstallment}><label>Pedido<input name="orderId" type="number" min="1" required /></label><label>Valor recebido<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Método<select name="method"><option value="PIX_MANUAL">Pix manual</option><option value="CREDIT_CARD_PHYSICAL">Cartão físico</option></select></label><label className="wide-field">Justificativa<textarea name="justification" required /></label><button type="submit">Enviar para análise</button></form></section>
    {canApprove && <section className="student-card"><h2>Pagamentos em análise</h2><div className="student-list">{resource.data?.reviews.map((review) => <article key={review.id}><div><strong>{review.order.student.person.name} · Pedido #{review.orderId}</strong><small>{review.method} · {money.format(Number(review.amount))} · {review.justification}</small></div><button type="button" onClick={() => void run(() => storeOperations.approve(review.id, 'Conferido pela administração'))}>Aprovar</button></article>)}</div>{resource.data?.reviews.length === 0 && <p>Nenhum pagamento em análise.</p>}<p><strong>ATENÇÃO:</strong> cancelar ou estornar poderá alterar o valor financeiro da venda. Confirme se o valor será estornado, convertido em mensalidade ou utilizado em outro produto.</p><form className="inline-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.cancel(Number(data.get('orderId')), String(data.get('reason')), data.get('restock') === 'on')); }}><label>Pedido<input name="orderId" type="number" min="1" required /></label><label>Justificativa<input name="reason" required /></label><label><input name="restock" type="checkbox" /> Repor estoque</label><label><input name="confirm" type="checkbox" required /> Confirmo o impacto financeiro</label><button type="submit">Cancelar pedido</button></form><form className="inline-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void run(() => storeOperations.refund(Number(data.get('paymentId')), String(data.get('reason')))); }}><label>Pagamento<input name="paymentId" type="number" min="1" required /></label><label>Justificativa<input name="reason" required /></label><label><input name="confirm" type="checkbox" required /> Confirmo o impacto financeiro</label><button type="submit">Registrar estorno manual</button></form></section>}
  </main>;
}
