import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ResourceState } from '../components/self-service/ResourceState';
import { useSelfServiceResource } from '../hooks';
import { selfService } from '../services';

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeZone: 'UTC' });
const orderLabels: Record<string, string> = { PENDING_PAYMENT: 'Pagamento pendente', PAYMENT_REVIEW: 'Pagamento em análise', CONFIRMED: 'Pagamento confirmado', IN_PRODUCTION: 'Em fabricação', AWAITING_DELIVERY: 'Aguardando entrega', READY_FOR_PICKUP: 'Venha buscar seu produto', COMPLETED: 'Concluído', CANCELLED: 'Cancelado' };
const paymentLabels: Record<string, string> = { PIX_QR_CODE: 'Pix QR Code', CREDIT_CARD_LINK: 'Link de cartão', CREDIT_CARD_PHYSICAL: 'Cartão físico', PIX_MANUAL: 'Pix manual', PENDING: 'Pendente', UNDER_REVIEW: 'Em análise', CONFIRMED: 'Confirmado', FAILED: 'Não confirmado', CANCELLED: 'Cancelado', REFUNDED: 'Estornado' };
const StoreHeader = ({ title, description }: { title: string; description: string }) => <header className="student-page-header"><p className="student-store-eyebrow">Loja WG</p><h1>{title}</h1><p>{description}</p></header>;
const StoreLinks = () => <nav className="student-store-links" aria-label="Navegação da Loja"><Link to="/app/shop">Catálogo</Link><Link to="/app/shop/cart">Carrinho</Link><Link to="/app/shop/orders">Pedidos</Link></nav>;
const PausedStoreNotice = () => <div className="student-status-banner" role="status"><strong>Consulta disponível</strong><br />Enquanto sua matrícula estiver pausada, você pode ver produtos e pedidos, mas não pode iniciar ou alterar compras.</div>;
const MutationMessage = ({ message, error = false }: { message: string; error?: boolean }) => message ? <p className={error ? 'student-action-message student-action-error' : 'student-action-message'} role={error ? 'alert' : 'status'}>{message}</p> : null;
const Status = ({ value }: { value: string }) => <span className={`student-pill store-status store-status-${value.toLowerCase()}`}>{orderLabels[value] ?? value.replace(/_/g, ' ')}</span>;

function ProductImage({ productId, name }: { productId: number; name: string }) {
  const [source, setSource] = useState('');
  useEffect(() => {
    let active = true;
    let objectUrl = '';
    void selfService.storeProductImage(productId).then((blob) => {
      if (!active) return;
      objectUrl = URL.createObjectURL(blob);
      setSource(objectUrl);
    }).catch(() => undefined);
    return () => {
      active = false;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
  }, [productId]);
  return source ? <img src={source} alt={`Foto de ${name}`} /> : <div className="store-image-placeholder" aria-hidden="true">WG</div>;
}

export function StudentStorePage() {
  const [search, setSearch] = useState('');
  const load = useCallback(async () => { const [me, products] = await Promise.all([selfService.me(), selfService.storeProducts()]); return { me, products }; }, []);
  const resource = useSelfServiceResource(load, [load]);
  const products = useMemo(() => { const term = search.trim().toLocaleLowerCase('pt-BR'); return resource.data?.products.filter((product) => !term || `${product.name} ${product.description}`.toLocaleLowerCase('pt-BR').includes(term)) ?? []; }, [resource.data, search]);
  return <><StoreHeader title="Catálogo" description="Escolha seu produto. Preços e disponibilidade são sempre confirmados pela academia." /><StoreLinks /><ResourceState {...resource} empty={false} onRetry={() => void resource.refresh()}>{resource.data && <>{resource.data.me.student.status === 'PAUSED' && <PausedStoreNotice />}<label className="student-store-search">Buscar produtos<input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nome ou descrição" /></label>{products.length === 0 ? <section className="student-state"><p>{search ? 'Nenhum produto corresponde à busca.' : 'Nenhum produto disponível no momento.'}</p></section> : <section className="student-product-grid" aria-label="Produtos disponíveis">{products.map((product) => <article className="student-product-card" key={product.id}>{product.imageUrl ? <ProductImage productId={product.id} name={product.name} /> : <div className="store-image-placeholder" aria-hidden="true">WG</div>}<div><h2>{product.name}</h2><p>{product.description}</p></div><strong>{currency.format(product.price)}</strong><span className={product.available ? 'student-pill student-pill-active' : 'student-pill'}>{product.madeToOrder ? 'Sob encomenda' : product.available ? 'Disponível' : 'Sem estoque'}</span><Link to={`/app/shop/products/${product.id}`}>Ver produto</Link></article>)}</section>}</>}</ResourceState></>;
}

export function StudentProductPage() {
  const productId = Number(useParams().productId); const [message, setMessage] = useState(''); const [failed, setFailed] = useState(false); const [variantId, setVariantId] = useState(''); const [quantity, setQuantity] = useState(1);
  const load = useCallback(async () => { const [me, product] = await Promise.all([selfService.me(), selfService.storeProduct(productId)]); return { me, product }; }, [productId]);
  const resource = useSelfServiceResource(load, [load]); const paused = resource.data?.me.student.status === 'PAUSED';
  const add = async () => { setMessage(''); try { const selected = Number(variantId || resource.data?.product.variants.find((variant) => variant.available)?.id); if (!selected) throw new Error('Selecione uma variação disponível.'); await selfService.addCartItem(productId, selected, quantity); setFailed(false); setMessage('Produto adicionado ao carrinho.'); } catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : 'Não foi possível alterar o carrinho.'); } };
  return <><StoreHeader title="Produto" description="Confira variação, quantidade e disponibilidade antes de adicionar." /><StoreLinks /><ResourceState {...resource} onRetry={() => void resource.refresh()}>{resource.data && <section className="student-card student-product-detail">{paused && <PausedStoreNotice />}{resource.data.product.imageUrl ? <ProductImage productId={resource.data.product.id} name={resource.data.product.name} /> : <div className="store-image-placeholder" aria-hidden="true">WG</div>}<h2>{resource.data.product.name}</h2><p>{resource.data.product.description}</p><strong className="student-product-price">{currency.format(resource.data.product.price)}</strong><span className={resource.data.product.available ? 'student-pill student-pill-active' : 'student-pill'}>{resource.data.product.madeToOrder ? 'Sob encomenda' : resource.data.product.available ? 'Disponível' : 'Sem estoque'}</span>{resource.data.product.madeToOrder && <p>Sob encomenda · prazo estimado de até {resource.data.product.leadTimeDays} dias.</p>}<div className="store-selection"><label>Cor e tamanho<select aria-label="Variação" value={variantId} onChange={(event) => setVariantId(event.target.value)}><option value="">Selecione</option>{resource.data.product.variants.map((variant) => <option key={variant.id} value={variant.id} disabled={!variant.available}>{[variant.color, variant.size].filter(Boolean).join(' · ') || 'Padrão'}{!variant.available ? ' — indisponível' : ''}</option>)}</select></label><label>Quantidade<input aria-label="Quantidade" type="number" min="1" max="99" value={quantity} onChange={(event) => setQuantity(Math.max(1, Number(event.target.value)))} /></label></div>{!paused && resource.data.product.available && <button type="button" onClick={() => void add()}>Adicionar ao carrinho</button>}<MutationMessage message={message} error={failed} /></section>}</ResourceState></>;
}

export function StudentCartPage() {
  const load = useCallback(async () => { const [me, cart] = await Promise.all([selfService.me(), selfService.cart()]); return { me, cart }; }, []); const resource = useSelfServiceResource(load, [load]); const [message, setMessage] = useState(''); const [failed, setFailed] = useState(false); const [method, setMethod] = useState<'PIX_QR_CODE' | 'CREDIT_CARD_LINK'>('PIX_QR_CODE'); const paused = resource.data?.me.student.status === 'PAUSED';
  const mutate = async (operation: () => Promise<unknown>, success?: string) => { setMessage(''); try { await operation(); setFailed(false); setMessage(success ?? 'Carrinho atualizado.'); await resource.refresh(); } catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : 'Não foi possível concluir.'); } };
  const update = (event: FormEvent<HTMLFormElement>, itemId: number) => { event.preventDefault(); void mutate(() => selfService.updateCartItem(itemId, Number(new FormData(event.currentTarget).get('quantity')))); };
  return <><StoreHeader title="Carrinho" description="Revise sua seleção. Os valores abaixo foram calculados pelo servidor." /><StoreLinks /><ResourceState {...resource} empty={Boolean(resource.data && resource.data.cart.items.length === 0)} emptyMessage="Seu carrinho está vazio." onRetry={() => void resource.refresh()}>{resource.data && <>{paused && <PausedStoreNotice />}<MutationMessage message={message} error={failed} /><section className="student-list student-cart-list">{resource.data.cart.items.map((item) => <article key={item.id}><div><strong>{item.product.name}</strong><small>{[item.variant.color, item.variant.size].filter(Boolean).join(' · ') || 'Padrão'}</small><small>{currency.format(item.unitPrice)} por unidade · Subtotal {currency.format(item.subtotal)}</small>{!item.available && <small className="student-action-error">Quantidade indisponível no momento.</small>}</div>{paused ? <span>Qtd. {item.quantity}</span> : <form onSubmit={(event) => update(event, item.id)} className="student-cart-actions"><label><span className="student-visually-hidden">Quantidade de {item.product.name}</span><input name="quantity" type="number" min="1" defaultValue={item.quantity} /></label><button type="submit">Atualizar</button><button type="button" className="student-button-secondary" onClick={() => void mutate(() => selfService.removeCartItem(item.id))}>Remover</button></form>}</article>)}</section><section className="student-card student-cart-total"><span>Total</span><strong>{currency.format(resource.data.cart.total)}</strong>{!paused && <><label>Forma de pagamento<select value={method} onChange={(event) => setMethod(event.target.value as typeof method)}><option value="PIX_QR_CODE">Pix QR Code</option><option value="CREDIT_CARD_LINK">Link de cartão</option></select></label><div className="store-cart-footer"><Link to="/app/shop">Continuar comprando</Link><button type="button" disabled={resource.data.cart.items.some((item) => !item.available)} onClick={() => void mutate(() => selfService.checkout(method, resource.data!.cart.total), 'Pedido criado. Acompanhe o status em Pedidos.')}>Revisar e criar pedido</button></div></>}<p>Pagamentos eletrônicos permanecem pendentes até confirmação por integração real. Pagamentos manuais ou físicos devem ser informados pela recepção.</p></section></>}</ResourceState></>;
}

export function StudentOrdersPage() { const load = useCallback(() => selfService.orders(), []); const resource = useSelfServiceResource(load, [load]); return <><StoreHeader title="Seus pedidos" description="Acompanhe pedidos comerciais sem misturá-los ao financeiro acadêmico." /><StoreLinks /><ResourceState {...resource} empty={Boolean(resource.data && resource.data.length === 0)} emptyMessage="Você ainda não possui pedidos." onRetry={() => void resource.refresh()}>{resource.data && <section className="student-list">{resource.data.map((order) => <article key={order.id}><div><strong>Pedido #{order.id}</strong><small>{date.format(new Date(order.createdAt))} · {order.itemCount} item(ns)</small><Status value={order.status} /></div><div><strong>{currency.format(order.total)}</strong><small>Saldo {currency.format(order.balance)}</small><Link to={`/app/shop/orders/${order.id}`}>Ver acompanhamento</Link></div></article>)}</section>}</ResourceState></>; }

export function StudentOrderPage() { const orderId = Number(useParams().orderId); const load = useCallback(() => selfService.order(orderId), [orderId]); const resource = useSelfServiceResource(load, [load]); return <><StoreHeader title={`Pedido #${orderId}`} description="Itens, pagamentos e andamento do seu pedido." /><StoreLinks /><ResourceState {...resource} onRetry={() => void resource.refresh()}>{resource.data && <div className="student-grid"><section className="student-card store-order-summary"><div><p>{date.format(new Date(resource.data.createdAt))}</p><Status value={resource.data.status} /></div><dl><div><dt>Total</dt><dd>{currency.format(resource.data.total)}</dd></div><div><dt>Pago</dt><dd>{currency.format(resource.data.paid)}</dd></div><div><dt>Pendente</dt><dd>{currency.format(resource.data.balance)}</dd></div></dl>{['IN_PRODUCTION', 'AWAITING_DELIVERY', 'READY_FOR_PICKUP'].includes(resource.data.status) && <p className="store-progress-note">A academia atualizará este acompanhamento conforme a encomenda avançar.</p>}</section><section className="student-list" aria-label="Itens do pedido">{resource.data.items.map((item) => <article key={item.id}><div><strong>{item.productName}</strong><small>{[item.color, item.size].filter(Boolean).join(' · ') || 'Padrão'} · {item.quantity} × {currency.format(item.unitPrice)}</small>{item.madeToOrder && item.leadTimeDays && <small>Prazo estimado: até {item.leadTimeDays} dias</small>}</div><strong>{currency.format(item.subtotal)}</strong></article>)}</section><section className="student-card"><h2>Pagamentos</h2>{resource.data.payments.length ? <div className="student-list">{resource.data.payments.map((payment) => <article key={payment.id}><div><strong>{paymentLabels[payment.method] ?? payment.method}</strong><small>{paymentLabels[payment.status] ?? payment.status}</small></div><strong>{currency.format(payment.amount)}</strong></article>)}</div> : <p>Nenhum pagamento registrado.</p>}</section></div>}</ResourceState></>; }
