import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApiRequest, useAuth } from '../hooks';
import { catalogService, studentService } from '../services';
import type { ApiListResponse, ModalityOption, Student, StudentStatus } from '../types';

const statuses: Record<StudentStatus, { className: string; label: string }> = { ACTIVE: { className: 'active', label: 'Ativo' }, PAUSED: { className: 'paused', label: 'Pausado' }, INACTIVE: { className: 'inactive', label: 'Inativo' } };

export function StudentsPage() {
  const navigate = useNavigate(); const { logout, user } = useAuth();
  const { data, error, loading, execute } = useApiRequest<ApiListResponse<Student>, [Parameters<typeof studentService.getAll>[0]]>();
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [modalityId, setModalityId] = useState(''); const [sort, setSort] = useState('name:asc'); const [page, setPage] = useState(1); const [modalities, setModalities] = useState<ModalityOption[]>([]);
  useEffect(() => { void catalogService.getModalities().then(setModalities).catch(() => undefined); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { const [sortBy, sortOrder] = sort.split(':'); void execute(studentService.getAll, { search: search || undefined, status: status || undefined, modalityId: modalityId ? Number(modalityId) : undefined, sortBy, sortOrder, page, pageSize: 20 }).catch(() => undefined); }, 250); return () => window.clearTimeout(timer); }, [execute, modalityId, page, search, sort, status]);
  const students = data?.data ?? [];
  return <main className="students-page">
    <div className="session-bar"><span>Conectado como <strong>{user?.name}</strong></span><button type="button" onClick={() => { logout(); navigate('/login', { replace: true }); }}>Sair</button></div>
    <header className="students-page-header"><div><p className="section-eyebrow">Recepção</p><h1>Alunos</h1><p>Pesquise e acesse a Central do Aluno.</p></div><div className="students-header-actions">{!loading && !error && <span>{data?.total ?? 0} aluno(s)</span>}{(user?.role === 'OWNER' || user?.role === 'ADMIN') && <button type="button" className="secondary-action-button" onClick={() => navigate('/admin')}>Administração</button>}<button type="button" className="secondary-action-button" onClick={() => navigate('/attendance')}>Realizar chamada</button>{user?.role !== 'TEACHER' && <button type="button" className="open-student-button" onClick={() => navigate('/students/new')}>Novo aluno</button>}</div></header>
    <section className="students-list-card"><div className="students-filters"><label className="students-search"><span>Pesquisar aluno</span><input type="search" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Nome, matrícula ou CPF" /></label><label>Status<select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Todos</option><option value="ACTIVE">Ativo</option><option value="PAUSED">Pausado</option><option value="INACTIVE">Inativo</option></select></label><label>Modalidade<select value={modalityId} onChange={(e) => { setModalityId(e.target.value); setPage(1); }}><option value="">Todas</option>{modalities.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Ordenar<select value={sort} onChange={(e) => { setSort(e.target.value); setPage(1); }}><option value="name:asc">Nome A-Z</option><option value="name:desc">Nome Z-A</option><option value="enrollmentNumber:asc">Matrícula</option><option value="joinedAt:desc">Mais recentes</option><option value="status:asc">Status</option></select></label></div>
    {loading && <div className="students-list-state"><span className="loading-spinner" /><p>Carregando alunos...</p></div>}
    {error && <div className="students-list-state students-list-error" role="alert"><strong>Não foi possível carregar os alunos.</strong><p>{error.message}</p></div>}
    {!loading && !error && students.length === 0 && <div className="students-list-state"><strong>Nenhum aluno encontrado</strong><p>Revise os filtros da pesquisa.</p></div>}
    {!loading && !error && students.length > 0 && <div className="students-table-scroll"><table className="students-table"><thead><tr><th>Matrícula</th><th>Nome</th><th>CPF</th><th>Modalidades</th><th>Status</th><th>Ações</th></tr></thead><tbody>{students.map((student) => { const detail = statuses[student.status]; return <tr key={student.id}><td><strong>{student.enrollmentNumber}</strong></td><td>{student.person.name}</td><td>{student.person.cpf}</td><td>{student.modalities?.map(({ modality }) => modality.name).join(', ') || <span className="students-unavailable">Não disponível</span>}</td><td><span className={`students-status ${detail.className}`}>{detail.label}</span></td><td><button className="open-student-button" type="button" onClick={() => navigate(`/students/${student.id}`)}>Abrir Central</button></td></tr>; })}</tbody></table></div>}
    {!loading && !error && (data?.totalPages ?? 0) > 1 && <nav className="students-pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {data?.page} de {data?.totalPages}</span><button disabled={page === data?.totalPages} onClick={() => setPage(page + 1)}>Próxima</button></nav>}
    </section>
  </main>;
}
